s=set() #empty set
n=int(input("Enter your number:"))
s.add(n)
n=int(input("Enter your number:"))
s.add(n)
n=int(input("Enter your number:"))
s.add(n)
n=int(input("Enter your number:"))
s.add(n)
n=int(input("Enter your number:"))
s.add(n)
n=int(input("Enter your number:"))
s.add(n)
n=int(input("Enter your number:"))
s.add(n)
n=int(input("Enter your number:"))
s.add(n)

print(s)